server.port=9090

spring.datasource.url=jdbc:h2:mem:testdb
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# 🔐 ADD THIS
groq.api.key=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
